language: go

go:
  - "1.11"

os:
  - linux

services:
  - docker

cache:
  directories:
    - ${GOPATH}/pkg/mod

jobs:
  include:
    - stage: test
      if: type == pull_request
      script: make services test
      env:
        - GO111MODULE=on

    - stage: test_and_cover
      name: "Test (with coverage)"
      if: type != pull_request
      script: make services cover
      env:
        - GO111MODULE=on
